call validate  ..\xsdrt\maindoc\UBL-TransportationStatus-2.3.xsd ..\xml\MyTransportationStatus.xml
call validate  ..\xsdrt\maindoc\UBL-BusinessCard-2.3.xsd ..\xml\UBL-BusinessCard-2.2-Example.xml
call validate  ..\xsdrt\maindoc\UBL-CreditNote-2.3.xsd ..\xml\UBL-CreditNote-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-CreditNote-2.3.xsd ..\xml\UBL-CreditNote-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-DebitNote-2.3.xsd ..\xml\UBL-DebitNote-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-DespatchAdvice-2.3.xsd ..\xml\UBL-DespatchAdvice-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-DigitalAgreement-2.3.xsd ..\xml\UBL-DigitalAgreement-2.2-Example-Multilateral.xml
call validate  ..\xsdrt\maindoc\UBL-DigitalAgreement-2.3.xsd ..\xml\UBL-DigitalAgreement-2.2-Example.xml
call validate  ..\xsdrt\maindoc\UBL-DigitalCapability-2.3.xsd ..\xml\UBL-DigitalCapability-2.2-Example.xml
call validate  ..\xsdrt\maindoc\UBL-ExceptionCriteria-2.3.xsd ..\xml\UBL-ExceptionCriteria-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-ExceptionNotification-2.3.xsd ..\xml\UBL-ExceptionNotification-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-ExpressionOfInterestRequest-2.3.xsd ..\xml\UBL-ExpressionOfInterestRequest-2.2-Example.xml
call validate  ..\xsdrt\maindoc\UBL-Forecast-2.3.xsd ..\xml\UBL-Forecast-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-ForecastRevision-2.3.xsd ..\xml\UBL-ForecastRevision-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-ForwardingInstructions-2.3.xsd ..\xml\UBL-ForwardingInstructions-2.0-Example-International.xml
call validate  ..\xsdrt\maindoc\UBL-FreightInvoice-2.3.xsd ..\xml\UBL-FreightInvoice-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-FulfilmentCancellation-2.3.xsd ..\xml\UBL-FulfilmentCancellation-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-GoodsItemItinerary-2.3.xsd ..\xml\UBL-GoodsItemItinerary-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-InstructionForReturns-2.3.xsd ..\xml\UBL-InstructionForReturns-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-InventoryReport-2.3.xsd ..\xml\UBL-InventoryReport-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-Invoice-2.3.xsd ..\xml\UBL-Invoice-2.0-Detached.xml
call validate  ..\xsdrt\maindoc\UBL-Invoice-2.3.xsd ..\xml\UBL-Invoice-2.0-Enveloped.xml
call validate  ..\xsdrt\maindoc\UBL-Invoice-2.3.xsd ..\xml\UBL-Invoice-2.0-Example-NS1.xml
call validate  ..\xsdrt\maindoc\UBL-Invoice-2.3.xsd ..\xml\UBL-Invoice-2.0-Example-NS2.xml
call validate  ..\xsdrt\maindoc\UBL-Invoice-2.3.xsd ..\xml\UBL-Invoice-2.0-Example-NS3.xml
call validate  ..\xsdrt\maindoc\UBL-Invoice-2.3.xsd ..\xml\UBL-Invoice-2.0-Example-NS4.xml
call validate  ..\xsdrt\maindoc\UBL-Invoice-2.3.xsd ..\xml\UBL-Invoice-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-Invoice-2.3.xsd ..\xml\UBL-Invoice-2.1-Example-Trivial.xml
call validate  ..\xsdrt\maindoc\UBL-Invoice-2.3.xsd ..\xml\UBL-Invoice-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-Order-2.3.xsd ..\xml\UBL-Order-2.0-Example-International.xml
call validate  ..\xsdrt\maindoc\UBL-Order-2.3.xsd ..\xml\UBL-Order-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-Order-2.3.xsd ..\xml\UBL-Order-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-OrderCancellation-2.3.xsd ..\xml\UBL-OrderCancellation-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-OrderChange-2.3.xsd ..\xml\UBL-OrderChange-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-OrderResponse-2.3.xsd ..\xml\UBL-OrderResponse-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-OrderResponseSimple-2.3.xsd ..\xml\UBL-OrderResponseSimple-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-OrderResponseSimple-2.3.xsd ..\xml\UBL-OrderResponseSimple-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-PriorInformationNotice-2.3.xsd ..\xml\UBL-PriorInformationNotice-2.2-Example-Embedded.xml
call validate  ..\xsdrt\maindoc\UBL-PriorInformationNotice-2.3.xsd ..\xml\UBL-PriorInformationNotice-2.2-Example-External.xml
call validate  ..\xsdrt\maindoc\UBL-ProductActivity-2.3.xsd ..\xml\UBL-ProductActivity-2.1-Example-1.xml
call validate  ..\xsdrt\maindoc\UBL-ProductActivity-2.3.xsd ..\xml\UBL-ProductActivity-2.1-Example-2.xml
call validate  ..\xsdrt\maindoc\UBL-ProductActivity-2.3.xsd ..\xml\UBL-ProductActivity-2.1-Example-3.xml
call validate  ..\xsdrt\maindoc\UBL-Quotation-2.3.xsd ..\xml\UBL-Quotation-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-Quotation-2.3.xsd ..\xml\UBL-Quotation-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-ReceiptAdvice-2.3.xsd ..\xml\UBL-ReceiptAdvice-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-Reminder-2.3.xsd ..\xml\UBL-Reminder-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-RemittanceAdvice-2.3.xsd ..\xml\UBL-RemittanceAdvice-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-RequestForQuotation-2.3.xsd ..\xml\UBL-RequestForQuotation-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-RequestForQuotation-2.3.xsd ..\xml\UBL-RequestForQuotation-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-RetailEvent-2.3.xsd ..\xml\UBL-RetailEvent-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-SelfBilledCreditNote-2.3.xsd ..\xml\UBL-SelfBilledCreditNote-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-Statement-2.3.xsd ..\xml\UBL-Statement-2.0-Example.xml
call validate  ..\xsdrt\maindoc\UBL-StockAvailabilityReport-2.3.xsd ..\xml\UBL-StockAvailabilityReport-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-TradeItemLocationProfile-2.3.xsd ..\xml\UBL-TradeItemLocationProfile-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-TransportExecutionPlan-2.3.xsd ..\xml\UBL-TransportExecutionPlan-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-TransportExecutionPlanRequest-2.3.xsd ..\xml\UBL-TransportExecutionPlanRequest-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-TransportProgressStatus-2.3.xsd ..\xml\UBL-TransportProgressStatus-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-TransportProgressStatusRequest-2.3.xsd ..\xml\UBL-TransportProgressStatusRequest-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-TransportServiceDescription-2.3.xsd ..\xml\UBL-TransportServiceDescription-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-TransportServiceDescriptionRequest-2.3.xsd ..\xml\UBL-TransportServiceDescriptionRequest-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-TransportationStatus-2.3.xsd ..\xml\UBL-TransportationStatus-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-TransportationStatusRequest-2.3.xsd ..\xml\UBL-TransportationStatusRequest-2.1-Example.xml
call validate  ..\xsdrt\maindoc\UBL-Waybill-2.3.xsd ..\xml\UBL-Waybill-2.0-Example-International.xml
call validate  ..\xsdrt\maindoc\UBL-WeightStatement-2.3.xsd ..\xml\UBL-WeightStatement-2.2-Example.xml
